import { useState } from 'react';
import { Bell, LogOut, ShieldCheck, UserRound } from 'lucide-react';
import { supabase } from '../../lib/supabase';

export default function AdminSettings() {
  const [signingOut,setSigningOut]=useState(false);
  const signOut=async()=>{setSigningOut(true);await supabase.auth.signOut();setSigningOut(false);};
  return <div><div className="dhl-admin-page-head"><div><span className="dhl-admin-eyebrow">ADMINISTRATION</span><h1>Settings</h1><p>Secure account and operations preferences.</p></div></div><div className="dhl-admin-settings-grid"><section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Admin profile</h2><UserRound size={18}/></div><div className="dhl-admin-settings-body"><p>Manage your session through the authenticated DHL admin account.</p><button type="button" className="dhl-admin-button" onClick={()=>void signOut()} disabled={signingOut}><LogOut size={16}/>{signingOut?'Signing out...':'Sign out'}</button></div></section><section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Notifications</h2><Bell size={18}/></div><div className="dhl-admin-settings-body"><p>Shipment and chat notifications are generated by the existing event pipeline. Delivery records and retries are managed in Notification Center.</p></div></section><section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Security</h2><ShieldCheck size={18}/></div><div className="dhl-admin-settings-body"><p>Admin access is checked against your authenticated role. Backend credentials and service secrets are never editable in the browser.</p></div></section></div></div>;
}
