import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Clock3, FileText, MapPin, MessageCircle, Package, Pencil, ShieldCheck, Truck, UserRound } from 'lucide-react';
import { useShipmentWithCheckpoints } from '../../hooks/useSupabase';
import { supabase } from '../../lib/supabase';
import AdminDetail from './AdminDetail';

type Tab = 'overview'|'tracking'|'customer'|'documents'|'history'|'controls';
type HistoryRow = {id:string;previous_status:string|null;new_status:string;customer_visible_reason:string|null;created_at:string};
const tabs:Tab[] = ['overview','tracking','customer','documents','history','controls'];
const name = (value:string) => value.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());
const date = (value?:string|null) => value?new Date(value).toLocaleString():'Not provided';

export default function AdminShipmentDetail() {
  const {id} = useParams<{id:string}>();
  const {shipment,loading} = useShipmentWithCheckpoints(id||'');
  const [tab,setTab] = useState<Tab>('overview');
  const [history,setHistory] = useState<HistoryRow[]>([]);
  const [historyError,setHistoryError] = useState('');
  useEffect(()=>{if(!id)return;let active=true;void (async()=>{const {data,error}=await supabase.from('shipment_status_history').select('id,previous_status,new_status,customer_visible_reason,created_at').eq('shipment_id',id).order('created_at',{ascending:false}).limit(100);if(!active)return;setHistory((data||[]) as HistoryRow[]);setHistoryError(error?'Status history is unavailable for this account.':'');})();return()=>{active=false;};},[id]);
  if(loading)return <div className="dhl-admin-empty"><Package size={25}/><strong>Loading shipment...</strong></div>;
  if(!shipment)return <div className="dhl-admin-empty"><Package size={25}/><strong>Shipment not found</strong><Link className="dhl-admin-button" to="/admin/shipments">Back to Shipments</Link></div>;
  const status=shipment.terminated?'terminated':shipment.stopped?'stopped':shipment.status||'processing';
  const tone=status==='delivered'?'delivered':status==='cancelled'||status==='delayed'||status==='stopped'||status==='terminated'?'alert':status==='in_transit'||status==='out_for_delivery'?'transit':'pending';
  const routeValue=shipment.route_screenshot_url;
  const routeImage=routeValue?(routeValue.startsWith('http')?routeValue:supabase.storage.from('route-screenshots').getPublicUrl(routeValue).data.publicUrl):'';
  const images=(shipment.images||[]).map(image=>image.startsWith('http')?image:supabase.storage.from('shipment-images').getPublicUrl(image).data.publicUrl);
  return <div className="dhl-admin-shipment-detail"><Link className="dhl-admin-detail-back" to="/admin/shipments"><ArrowLeft size={16}/> Back to Shipments</Link><div className="dhl-admin-page-head"><div><span className="dhl-admin-eyebrow">SHIPMENT CONTROL PANEL</span><h1>{shipment.package_name||'Shipment details'}</h1><p className="dhl-admin-detail-id">Tracking number: <strong>{shipment.id}</strong></p><div className="dhl-admin-detail-meta"><span className={`dhl-admin-status ${tone}`}>{name(status)}</span><span>Created {date(shipment.created_at)}</span>{shipment.is_published?<span>Published</span>:<span>Draft</span>}</div></div><div className="dhl-admin-page-actions"><Link className="dhl-admin-button" to={`/admin/shipments/${shipment.id}/edit`}><Pencil size={16}/> Edit Shipment</Link><button type="button" className="dhl-admin-button primary" onClick={()=>setTab('controls')}>Update Status</button><Link className="dhl-admin-button" to={`/admin/chat?tracking=${encodeURIComponent(shipment.id)}`}><MessageCircle size={16}/> Contact Customer</Link></div></div>
    <div className="dhl-admin-detail-tabs" role="tablist" aria-label="Shipment information">{tabs.map(value=><button type="button" role="tab" aria-selected={tab===value} className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}>{value==='controls'?'Lifecycle controls':name(value)}</button>)}</div>
    {tab==='overview'&&<div className="dhl-admin-detail-grid"><section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Shipment overview</h2><Package size={18}/></div><dl className="dhl-admin-detail-facts"><div><dt>Sender</dt><dd>{shipment.sender_name}</dd></div><div><dt>Recipient</dt><dd>{shipment.receiver_name}</dd></div><div><dt>Origin</dt><dd>{shipment.pickup_location||'Not provided'}</dd></div><div><dt>Destination</dt><dd>{shipment.delivery_address}</dd></div><div><dt>Transport</dt><dd>{shipment.transportation}</dd></div><div><dt>Vehicle type</dt><dd>{shipment.vehicle_type||'Not provided'}</dd></div><div><dt>Pieces / package</dt><dd>{shipment.package_name||'Not provided'}</dd></div><div><dt>Expected delivery</dt><dd>{date(shipment.estimated_delivery_at)}</dd></div><div><dt>Payment</dt><dd>{name(shipment.payment_status||'unpaid')} · {shipment.currency||'USD'} {shipment.cost||0}</dd></div></dl></section><aside className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Current journey</h2><Truck size={18}/></div><div className="dhl-admin-journey"><span className={`dhl-admin-status ${tone}`}>{name(status)}</span><p>{shipment.checkpoints?.length||0} recorded route milestones</p><div className="dhl-admin-journey-line"><span style={{width:`${shipment.checkpoints?.length?Math.round(((shipment.current_checkpoint_index||0)+1)/shipment.checkpoints.length*100):0}%`}}/></div><div><MapPin size={16}/>{shipment.checkpoints?.[shipment.current_checkpoint_index||0]?.location||shipment.pickup_location||'Origin not set'}</div><button type="button" className="dhl-admin-button" onClick={()=>setTab('tracking')}>View tracking timeline</button></div></aside></div>}
    {tab==='tracking'&&<div className="dhl-admin-detail-grid"><section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Tracking timeline</h2><Clock3 size={18}/></div>{shipment.checkpoints?.length?<ol className="dhl-admin-detail-timeline">{[...shipment.checkpoints].sort((a,b)=>a.checkpoint_order-b.checkpoint_order).map((point,index)=><li className={point.status} key={point.id}><span className="dhl-admin-timeline-node"/><div><strong>{point.location}</strong><small>Milestone {index+1} · {name(point.status)}</small></div><time>{date(point.updated_at)}</time></li>)}</ol>:<div className="dhl-admin-empty"><MapPin size={22}/><strong>No checkpoints recorded</strong></div>}</section><aside className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Route image</h2></div>{routeImage?<a href={routeImage} target="_blank" rel="noreferrer" className="dhl-admin-route-image"><img src={routeImage} alt="Recorded shipment route"/></a>:<div className="dhl-admin-empty"><MapPin size={22}/><strong>No route image attached</strong></div>}<div className="dhl-admin-detail-side-action"><button type="button" className="dhl-admin-button primary" onClick={()=>setTab('controls')}>Manage lifecycle & checkpoints</button></div></aside></div>}
    {tab==='customer'&&<div className="dhl-admin-detail-grid"><section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Sender</h2><UserRound size={18}/></div><dl className="dhl-admin-detail-facts"><div><dt>Name</dt><dd>{shipment.sender_name}</dd></div><div><dt>Email</dt><dd>{shipment.sender_email||'Not provided'}</dd></div><div><dt>Phone</dt><dd>{shipment.sender_phone}</dd></div><div><dt>Pickup</dt><dd>{shipment.pickup_location||'Not provided'}</dd></div></dl></section><section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Recipient</h2><UserRound size={18}/></div><dl className="dhl-admin-detail-facts"><div><dt>Name</dt><dd>{shipment.receiver_name}</dd></div><div><dt>Email</dt><dd>{shipment.receiver_email||'Not provided'}</dd></div><div><dt>Phone</dt><dd>{shipment.receiver_phone}</dd></div><div><dt>Delivery address</dt><dd>{shipment.delivery_address}</dd></div></dl></section></div>}
    {tab==='documents'&&<div className="dhl-admin-detail-grid"><section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Package images</h2><Package size={18}/></div>{images.length?<div className="dhl-admin-detail-images">{images.map((image,index)=><a key={image+index} href={image} target="_blank" rel="noreferrer"><img src={image} alt={`Package image ${index+1}`}/></a>)}</div>:<div className="dhl-admin-empty"><Package size={22}/><strong>No package images attached</strong></div>}</section><aside className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Documents & waybill</h2><FileText size={18}/></div><div className="dhl-admin-document-links"><Link to={`/track/${shipment.id}?view=waybill`}><FileText size={17}/> Waybill preview</Link>{routeImage&&<a href={routeImage} target="_blank" rel="noreferrer"><MapPin size={17}/> Route image</a>}<p>Waybill is a shipment-record preview; no carrier-issued PDF is stored unless separately attached.</p></div></aside></div>}
    {tab==='history'&&<section className="dhl-admin-card"><div className="dhl-admin-card-head"><h2>Status history</h2><ShieldCheck size={18}/></div>{historyError?<div className="dhl-admin-empty"><Clock3 size={22}/><strong>{historyError}</strong></div>:history.length?<ol className="dhl-admin-detail-timeline">{history.map(item=><li key={item.id}><span className="dhl-admin-timeline-node"/><div><strong>{name(item.new_status)}</strong><small>{item.previous_status?`${name(item.previous_status)} → `:''}{item.customer_visible_reason||'Status changed'}</small></div><time>{date(item.created_at)}</time></li>)}</ol>:<div className="dhl-admin-empty"><Clock3 size={22}/><strong>No status changes recorded</strong></div>}</section>}
    {tab==='controls'&&<div className="dhl-admin-detail-control"><AdminDetail/></div>}
  </div>;
}
