import { useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { Check, ChevronLeft, ChevronRight, FileText, ImagePlus, Package, Plane, Ship, Truck } from 'lucide-react';

export type ShipmentDraft = {
  senderName:string; senderPhone:string; senderEmail:string; pickupLocation:string;
  receiverName:string; receiverPhone:string; receiverEmail:string; deliveryAddress:string;
  packageName:string; transportation:string; images:string[]; imageFiles:File[];
  cost:string; currency:string; paymentStatus:'unpaid'|'pending'|'paid'; paymentResponsibility:'sender'|'receiver'|'company';
  vehicleType:string; vehiclesCount:string; driverName:string; driverExperience:string; countdownDuration:string; checkpoints:string[];
};
export const initialShipmentDraft:ShipmentDraft = { senderName:'',senderPhone:'',senderEmail:'',pickupLocation:'',receiverName:'',receiverPhone:'',receiverEmail:'',deliveryAddress:'',packageName:'',transportation:'Air Freight',images:['','',''],imageFiles:[],cost:'',currency:'USD',paymentStatus:'unpaid',paymentResponsibility:'sender',vehicleType:'',vehiclesCount:'',driverName:'',driverExperience:'',countdownDuration:'24',checkpoints:['','','','',''] };
const steps = ['Sender','Recipient','Shipment','Services','Review'];
const transports = [{value:'Air Freight',label:'Air Freight',icon:Plane},{value:'Ocean Cargo',label:'Ocean Cargo',icon:Ship},{value:'Land Transport',label:'Land Transport',icon:Truck},{value:'Door-to-Door Delivery',label:'Door-to-Door',icon:Package}];
type Props = { mode:'admin'|'public'; onSubmit:(draft:ShipmentDraft)=>Promise<void>; submitting:boolean; submitError:string };

export default function ShipmentWizard({mode,onSubmit,submitting,submitError}:Props) {
  const [step,setStep] = useState(0);
  const [draft,setDraft] = useState<ShipmentDraft>(initialShipmentDraft);
  const [error,setError] = useState('');
  const [imagePreview,setImagePreview] = useState<string[]>([]);
  const set = <K extends keyof ShipmentDraft>(key:K,value:ShipmentDraft[K]) => { setDraft(current=>({...current,[key]:value})); setError(''); };
  const imageUrls = useMemo(()=>draft.images.map(value=>value.trim()).filter(Boolean),[draft.images]);
  const validStep = (index:number) => {
    const required = index===0 ? [['senderName','Sender name'],['senderPhone','Sender phone'],['senderEmail','Sender email'],['pickupLocation','Pickup location']] : index===1 ? [['receiverName','Recipient name'],['receiverPhone','Recipient phone'],['receiverEmail','Recipient email'],['deliveryAddress','Delivery address']] : index===2 ? [['packageName','Package description']] : [];
    for (const [key,label] of required) if (!String(draft[key as keyof ShipmentDraft]||'').trim()) return `${label} is required.`;
    if (index===0 && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.senderEmail.trim())) return 'Enter a valid sender email address.';
    if (index===1 && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.receiverEmail.trim())) return 'Enter a valid recipient email address.';
    if (index===2 && mode==='admin' && imageUrls.length+draft.imageFiles.length<3) return 'Add at least 3 package images or image links.';
    if (index===2 && imageUrls.length+draft.imageFiles.length>6) return 'Use no more than 6 package images.';
    if (index===2 && imageUrls.some(url=>!/^https?:\/\//i.test(url))) return 'Image links must start with http or https.';
    if (index===3 && mode==='admin' && !draft.vehicleType.trim()) return 'Vehicle or aircraft type is required.';
    if (index===3 && mode==='admin' && draft.checkpoints.filter(Boolean).length<5) return 'Add at least 5 route milestones.';
    return '';
  };
  const next = () => { const issue=validStep(step); if(issue){setError(issue);return;} setStep(value=>Math.min(value+1,4)); window.scrollTo({top:0,behavior:'smooth'}); };
  const publish = async (event:FormEvent) => {event.preventDefault(); for(let index=0;index<4;index++){const issue=validStep(index);if(issue){setStep(index);setError(issue);return;}} await onSubmit({...draft,images:imageUrls});};
  const field = (label:string,key:keyof ShipmentDraft,options?:{type?:string;placeholder?:string;required?:boolean}) => <label className="dhl-admin-form-field"><span>{label}{options?.required&&<i> *</i>}</span><input type={options?.type||'text'} value={String(draft[key]||'')} onChange={event=>set(key,event.target.value as ShipmentDraft[typeof key])} placeholder={options?.placeholder||''} autoComplete="off" /></label>;
  const previews = [...imageUrls.map(url=>({key:url,url,label:'Image link'})),...draft.imageFiles.map((file,index)=>({key:`file-${index}`,url:imagePreview[index],label:file.name}))];
  return <div className="dhl-admin-wizard">
    <div className="dhl-admin-wizard-stepper" aria-label="Shipment form progress">{steps.map((label,index)=><button key={label} type="button" onClick={()=>{if(index<step){setStep(index);setError('');}}} className={index===step?'active':index<step?'done':''} aria-current={index===step?'step':undefined}><span>{index<step?<Check size={14}/>:index+1}</span><strong>{label}</strong></button>)}</div>
    <form onSubmit={publish} noValidate><div className="dhl-admin-wizard-panel">
      <div className="dhl-admin-wizard-heading"><span>STEP {step+1} OF 5</span><h2>{steps[step]}</h2><p>{['Who is sending this shipment?','Where is it going and who will receive it?','Describe the package and add its images.','Choose the transport, route and payment details.','Review every detail before the final action.'][step]}</p></div>
      {error&&<p className="dhl-admin-banner error" role="alert">{error}</p>}{submitError&&<p className="dhl-admin-banner error" role="alert">{submitError}</p>}
      {step===0&&<div className="dhl-admin-form-grid">{field('Full name','senderName',{required:true,placeholder:'Sender full name'})}{field('Phone','senderPhone',{required:true,placeholder:'+1 555 000 0000'})}{field('Email','senderEmail',{required:true,type:'email',placeholder:'sender@example.com'})}{field('Pickup address / origin','pickupLocation',{required:true,placeholder:'Street, city, state, country'})}</div>}
      {step===1&&<div className="dhl-admin-form-grid">{field('Full name','receiverName',{required:true,placeholder:'Recipient full name'})}{field('Phone','receiverPhone',{required:true,placeholder:'+1 555 000 0000'})}{field('Email','receiverEmail',{required:true,type:'email',placeholder:'recipient@example.com'})}{field('Delivery address / destination','deliveryAddress',{required:true,placeholder:'Street, city, state, country'})}</div>}
      {step===2&&<><div className="dhl-admin-form-grid">{field('Package name / description','packageName',{required:true,placeholder:'e.g. Documents, electronics, medical supplies'})}</div><div className="dhl-admin-form-divider"/><h3>Package images <small>{mode==='admin'?'At least 3, up to 6.':'Optional image links for review.'}</small></h3>{mode==='admin'&&<label className="dhl-admin-upload"><ImagePlus size={25}/><strong>Upload package images</strong><small>Select up to 6 images from your device</small><input type="file" accept="image/*" multiple onChange={event=>{const files=Array.from(event.target.files||[]).filter(file=>file.type.startsWith('image/')).slice(0,Math.max(0,6-imageUrls.length)); imagePreview.forEach(url=>URL.revokeObjectURL(url)); setImagePreview(files.map(file=>URL.createObjectURL(file))); set('imageFiles',files);}} /></label>}<div className="dhl-admin-form-grid">{draft.images.map((url,index)=><label className="dhl-admin-form-field" key={index}><span>Image URL {index+1}</span><input type="url" placeholder="https://..." value={url} onChange={event=>set('images',draft.images.map((item,i)=>i===index?event.target.value:item))} /></label>)}</div>{draft.images.length+draft.imageFiles.length<6&&<button className="dhl-admin-text-action" type="button" onClick={()=>set('images',[...draft.images,''])}>+ Add another image URL</button>}{previews.length>0&&<div className="dhl-admin-image-previews">{previews.map(item=><div key={item.key}><img src={item.url} alt={item.label} onError={event=>{event.currentTarget.style.display='none';}}/><span>{item.label}</span></div>)}</div>}</>}
      {step===3&&<><h3>Transportation method</h3><div className="dhl-admin-choice-grid">{transports.map(({value,label,icon:Icon})=><button type="button" key={value} className={draft.transportation===value?'selected':''} onClick={()=>set('transportation',value)}><Icon size={20}/><strong>{label}</strong></button>)}</div><div className="dhl-admin-form-grid">{field('Vehicle / aircraft / vessel type','vehicleType',{required:true,placeholder:'e.g. Cargo van, aircraft'})}{field('Number of vehicles','vehiclesCount',{type:'number',placeholder:'1'})}{field('Driver / pilot name','driverName',{placeholder:'Optional'})}{field('Experience','driverExperience',{placeholder:'Optional'})}{field('Estimated hours to arrival','countdownDuration',{type:'number',placeholder:'24'})}{field('Shipping cost','cost',{type:'number',placeholder:'0.00'})}<label className="dhl-admin-form-field"><span>Currency</span><select value={draft.currency} onChange={event=>set('currency',event.target.value)}><option>USD</option><option>EUR</option><option>GBP</option><option>NGN</option></select></label><label className="dhl-admin-form-field"><span>Payment responsibility</span><select value={draft.paymentResponsibility} onChange={event=>set('paymentResponsibility',event.target.value as ShipmentDraft['paymentResponsibility'])}><option value="sender">Sender</option><option value="receiver">Receiver</option><option value="company">Company</option></select></label><label className="dhl-admin-form-field"><span>Payment status</span><select value={draft.paymentStatus} onChange={event=>set('paymentStatus',event.target.value as ShipmentDraft['paymentStatus'])}><option value="unpaid">Unpaid</option><option value="pending">Awaiting payment</option><option value="paid">Paid</option></select></label></div><div className="dhl-admin-form-divider"/><h3>Route milestones <small>{mode==='admin'?'At least 5, up to 12.':'Add known locations if available.'}</small></h3><div className="dhl-admin-form-grid">{draft.checkpoints.map((location,index)=><label className="dhl-admin-form-field" key={index}><span>Milestone {index+1}</span><input value={location} onChange={event=>set('checkpoints',draft.checkpoints.map((item,i)=>i===index?event.target.value:item))} placeholder="City or facility" /></label>)}</div>{draft.checkpoints.length<12&&<button className="dhl-admin-text-action" type="button" onClick={()=>set('checkpoints',[...draft.checkpoints,''])}>+ Add milestone</button>}</>}
      {step===4&&<div className="dhl-admin-review"><section><div><h3>Sender</h3><button type="button" onClick={()=>setStep(0)}>Edit</button></div><p>{draft.senderName}<br/>{draft.senderEmail} · {draft.senderPhone}<br/>{draft.pickupLocation}</p></section><section><div><h3>Recipient</h3><button type="button" onClick={()=>setStep(1)}>Edit</button></div><p>{draft.receiverName}<br/>{draft.receiverEmail} · {draft.receiverPhone}<br/>{draft.deliveryAddress}</p></section><section><div><h3>Shipment</h3><button type="button" onClick={()=>setStep(2)}>Edit</button></div><p>{draft.packageName}<br/>{imageUrls.length+draft.imageFiles.length} package images</p></section><section><div><h3>Services & route</h3><button type="button" onClick={()=>setStep(3)}>Edit</button></div><p>{draft.transportation} · {draft.vehicleType}<br/>{draft.checkpoints.filter(Boolean).length} milestones · {draft.countdownDuration} hours ETA<br/>{draft.currency} {draft.cost||'0'} · {draft.paymentStatus}</p></section><div className="dhl-admin-review-note"><FileText size={18}/><span>{mode==='admin'?'Publishing creates an active shipment using the current DHL lifecycle.':'Submitting creates a pending request. No shipment becomes active until an admin approves it.'}</span></div></div>}
      <div className="dhl-admin-wizard-footer"><button type="button" className="dhl-admin-button" onClick={()=>{setStep(value=>Math.max(0,value-1));setError('');}} disabled={step===0}><ChevronLeft size={16}/> Back</button>{step<4?<button type="button" className="dhl-admin-button primary" onClick={next}>Next step <ChevronRight size={16}/></button>:<button type="submit" className="dhl-admin-button primary" disabled={submitting}>{submitting?'Processing...':mode==='admin'?'Publish Shipment':'Submit Request'} <ChevronRight size={16}/></button>}</div>
    </div></form>
  </div>;
}
