import i18n from 'i18next';
import { I18nextProvider, initReactI18next, useTranslation } from 'react-i18next';

export const languages = [
  { code: 'en', label: 'English', locale: 'en-US', dir: 'ltr' }, { code: 'fr', label: 'Français', locale: 'fr-FR', dir: 'ltr' },
  { code: 'es', label: 'Español', locale: 'es-ES', dir: 'ltr' }, { code: 'pt', label: 'Português', locale: 'pt-BR', dir: 'ltr' }, { code: 'ar', label: 'العربية', locale: 'ar', dir: 'rtl' },
] as const;
export type LanguageCode = typeof languages[number]['code'];
const key = 'shipment-language';
const en = { home: 'Home', track: 'Track Shipment', send: 'Send Shipment', support: 'Customer Support', notifications: 'Notifications', settings: 'Settings', help: 'Help Center', signIn: 'Sign in', language: 'Language', guest: 'Guest', guestHint: 'Track and manage your shipments', whatsapp: 'WhatsApp Support', trackingPlaceholder: 'Enter 12-digit tracking number', trackButton: 'Track Shipment', trackingDigits: 'Tracking numbers contain 12 digits.', trackingNumbersOnly: 'Tracking numbers can contain numbers only.', trackingComplete: 'Enter the complete 12-digit tracking number.',
  // Shipment wizard draft, uploads, publication and receipt.
  savingDraft: 'Saving draft…', draftSaved: 'Draft saved', draftRestored: 'Draft restored', discardDraft: 'Discard Draft',
  discardDraftConfirm: 'Discard this draft? The details and uploaded images you entered will be removed.',
  uploading: 'Uploading…', uploaded: 'Uploaded', uploadFailed: 'Upload failed', couldNotUpload: 'Could not upload', retryUpload: 'Retry upload',
  waitForUploads: 'Wait for the package images to finish uploading.', fixFailedUploads: 'Retry or remove the images that failed to upload.',
  shipmentPublished: 'Shipment Published Successfully', trackingId: 'Tracking ID', copyTrackingId: 'Copy Tracking ID',
  viewReceipt: 'View Receipt', printReceipt: 'Print Receipt', shipmentReceipt: 'Shipment Receipt', openControlPanel: 'Open Control Panel',
  trackAsCustomer: 'Track as Customer', publishedAt: 'Published' };
const resources = { en: { translation: en }, fr: { translation: { ...en, home: 'Accueil', track: 'Suivre un envoi', send: 'Envoyer un colis', support: 'Assistance client', settings: 'Paramètres', help: 'Centre d’aide', signIn: 'Se connecter', language: 'Langue', guest: 'Invité', guestHint: 'Suivez et gérez vos envois', whatsapp: 'Assistance WhatsApp', trackingPlaceholder: 'Saisissez le numéro à 12 chiffres', trackButton: 'Suivre l’envoi', trackingDigits: 'Les numéros de suivi comportent 12 chiffres.', trackingNumbersOnly: 'Les numéros de suivi ne contiennent que des chiffres.', trackingComplete: 'Saisissez le numéro de suivi complet à 12 chiffres.' } }, es: { translation: { ...en, home: 'Inicio', track: 'Rastrear envío', send: 'Enviar paquete', support: 'Atención al cliente', settings: 'Configuración', help: 'Centro de ayuda', signIn: 'Iniciar sesión', language: 'Idioma', guest: 'Invitado', guestHint: 'Rastrea y gestiona tus envíos', whatsapp: 'Soporte por WhatsApp', trackingPlaceholder: 'Introduce el número de 12 dígitos', trackButton: 'Rastrear envío' } }, pt: { translation: { ...en, home: 'Início', track: 'Rastrear envio', send: 'Enviar remessa', support: 'Suporte ao cliente', settings: 'Configurações', help: 'Central de ajuda', signIn: 'Entrar', language: 'Idioma', guest: 'Visitante', guestHint: 'Rastreie e gerencie suas remessas', whatsapp: 'Suporte WhatsApp', trackingPlaceholder: 'Digite o número de 12 dígitos', trackButton: 'Rastrear envio' } }, ar: { translation: { ...en, home: 'الرئيسية', track: 'تتبع الشحنة', send: 'إرسال شحنة', support: 'دعم العملاء', settings: 'الإعدادات', help: 'مركز المساعدة', signIn: 'تسجيل الدخول', language: 'اللغة', guest: 'زائر', guestHint: 'تتبع شحناتك وأدرها', whatsapp: 'دعم واتساب', trackingPlaceholder: 'أدخل رقم التتبع المكوّن من 12 رقماً', trackButton: 'تتبع الشحنة' } } };
function initialLanguage(): LanguageCode { const saved = localStorage.getItem(key); if (languages.some(item => item.code === saved)) return saved as LanguageCode; const candidate = [...navigator.languages, navigator.language].find(value => languages.some(item => item.code === value.toLowerCase().split('-')[0])); return (candidate?.toLowerCase().split('-')[0] as LanguageCode) || 'en'; }
i18n.use(initReactI18next).init({ resources, lng: initialLanguage(), fallbackLng: 'en', interpolation: { escapeValue: false } });
function applyDocument(code: string) { const item = languages.find(language => language.code === code) || languages[0]; document.documentElement.lang = item.locale; document.documentElement.dir = item.dir; }
applyDocument(i18n.language);
i18n.on('languageChanged', code => { localStorage.setItem(key, code); applyDocument(code); });
export function I18nProvider({ children }: { children: React.ReactNode }) { return <I18nextProvider i18n={i18n}>{children}</I18nextProvider>; }
export function useI18n() { const { t, i18n: instance } = useTranslation(); const language = (languages.some(item => item.code === instance.language) ? instance.language : 'en') as LanguageCode; const current = languages.find(item => item.code === language)!; return { language, locale: current.locale, setLanguage: (code: LanguageCode) => void instance.changeLanguage(code), t: (name: keyof typeof en) => t(name) }; }
