-- Intentionally retained as a no-op historical marker. The clean baseline
-- never inserts a development administrator, so production migrations contain
-- no synthetic account identifiers or cleanup side effects.
